// Generated by CoffeeScript 1.6.3
(function() {
  this.GraphBuilder = (function() {
    function GraphBuilder(element_id, data) {
      this.sigma_instance = sigma.init(document.getElementById(element_id)).drawingProperties({
        defaultLabelColor: '#fff',
        defaultLabelSize: 14,
        defaultLabelBGColor: '#fff',
        defaultLabelHoverColor: '#000',
        labelThreshold: 1,
        defaultEdgeType: 'curve'
      }).graphProperties({
        minNodeSize: 0.5,
        maxNodeSize: 10,
        minEdgeSize: 1,
        maxEdgeSize: 1,
        sideMargin: 50
      }).mouseProperties({
        maxRatio: 32
      });
      this.service_nodes = data.service_nodes || {};
      this.device_nodes = data.device_nodes || {};
      this.service_edges = data.service_edges || {};
      this.device_service_edges = data.device_service_edges || {};
      this.service_device_edges = data.service_device_edges || {};
      this.node_frequency = this.nodeFrequency(this.service_edges.concat(this.device_service_edges, this.service_device_edges));
    }

    GraphBuilder.prototype.nodeId = function(label) {
      if (label != null) {
        return label = label.replace(/_/g, "-").toLowerCase();
      }
    };

    GraphBuilder.prototype.nodeFrequency = function(edges) {
      var result,
        _this = this;
      result = {};
      $(edges).each(function(idx, el) {
        result[_this.nodeId(el[0])] = +result[_this.nodeId(el[0])] + 1 || 1;
        return result[_this.nodeId(el[1])] = +result[_this.nodeId(el[1])] + 1 || 1;
      });
      return result;
    };

    GraphBuilder.prototype.createNodes = function(nodes, frequency, x_offset, radius) {
      var _this = this;
      frequency = frequency || {};
      x_offset = x_offset || 0;
      radius = radius || 200;
      nodes = nodes.filter(function(el) {
        return frequency[_this.nodeId(el[0])] > 0;
      });
      return $(nodes).each(function(idx, el) {
        return _this.sigma_instance.addNode(_this.nodeId(el[0]), {
          label: el[0],
          color: el[1],
          x: (Math.sin((Math.PI * 2) / nodes.length * idx) * radius) + x_offset,
          y: Math.cos((Math.PI * 2) / nodes.length * idx) * radius,
          size: 1 + (frequency[_this.nodeId(el[0])] || 0)
        });
      });
    };

    GraphBuilder.prototype.draw = function() {
      var _this = this;
      this.node_frequency;
      this.createNodes(this.service_nodes, this.node_frequency, 0, 150);
      this.createNodes(this.device_nodes, this.node_frequency, -400, 50);
      $(this.service_edges.concat(this.service_device_edges)).each(function(idx, el) {
        return _this.sigma_instance.addEdge(el.join('_'), el[0], el[1], {
          arrow: 'target'
        });
      });
      $(this.device_service_edges).each(function(idx, el) {
        return _this.sigma_instance.addEdge(el.join('_'), el[0], el[1], {
          arrow: 'target',
          type: 'line'
        });
      });
      this.sigma_instance.draw();
      return this;
    };

    return GraphBuilder;

  })();

}).call(this);
