// Generated by CoffeeScript 1.6.3
(function() {
  var GraphBuilder;

  GraphBuilder = (function() {
    function GraphBuilder(dom_element, data) {
      this.sigma_instance = sigma.init(dom_element).drawingProperties({
        defaultLabelColor: '#fff',
        defaultLabelSize: 14,
        defaultLabelBGColor: '#fff',
        defaultLabelHoverColor: '#000',
        labelThreshold: 1,
        defaultEdgeType: 'curve'
      }.graphProperties({
        minNodeSize: 0.5,
        maxNodeSize: 10,
        minEdgeSize: 1,
        maxEdgeSize: 1,
        sideMargin: 50
      }.mouseProperties({
        maxRatio: 32
      })));
      this.service_nodes = data.service_nodes || {};
      this.device_nodes = data.device_nodes || {};
      this.service_edges = data.service_edges || {};
      this.device_service_edges = data.device_service_nodes || {};
      this.service_device_edges = data.service_service_nodes || {};
    }

    GraphBuilder.prototype.nodeId = function(label) {
      if (label != null) {
        return label = label.replace(/_/g, "-").toLowerCase();
      }
    };

    GraphBuilder.prototype.nodeFrequency = function(edges) {
      var result,
        _this = this;
      result = {};
      $(edges).each(function(idx) {
        result[_this.nodeId(_this[0])] = +result[_this.nodeId(_this[0])] + 1 || 1;
        return result[_this.nodeId(_this[1])] = +result[_this.nodeId(_this[1])] + 1 || 1;
      });
      return result;
    };

    GraphBuilder.prototype.createNodes = function(nodes, frequency, x_offset, radius) {
      var _this = this;
      frequency = frequency || {};
      x_offset = x_offset || 0;
      radius = radius || 200;
      nodes = nodes.filter(function(el) {
        return frequency[_this.nodeId(el[0])] > 0;
      });
      return $(nodes).each(function(idx) {
        return _this.sigma_instante.addNode(_this.nodeId(_this[0]), {
          label: _this[0],
          color: _this[1],
          x: (Math.sin((Math.PI * 2) / nodes.length * idx) * radius) + x_offset,
          y: Math.cos((Math.PI * 2) / nodes.length * idx) * radius,
          size: 1 + (frequency[_this.nodeId(_this[0])] || 0)
        });
      });
    };

    GraphBuilder.prototype.draw = function() {
      var node_frequency,
        _this = this;
      node_frequency = this.nodeFrequency(this.service_edges.concat(this.device_service_edges, this.service_device_edges));
      this.createNodes(this.service_nodes, node_frequency, 0, 150);
      this.createNodes(this.device_nodess, node_frequency, -400, 50);
      $(this.service_edges.concat(this.service_device_edges)).each(function(idx) {
        return _this.sigma_instance.addEdge(_this.join('_'), _this[0], _this[1], {
          arrow: 'target'
        });
      });
      $(this.device_service_edges).each(function(idx) {
        return _this.sigma_instance.addEdge(_this.join('_'), _this[0], _this[1], {
          arrow: 'target',
          type: 'line'
        });
      });
      return this.sigma_instance.draw;
    };

    return GraphBuilder;

  })();

}).call(this);
